# Setup
title:               Cambrian Entropy
tagline:             'Taking a Step Back'
description:         'Business :: Finance :: Economics :: Music :: Documentaries :: Miscellany'
url:                 https://cambrianentropy.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Cambrian Entropy
  url:               https://twitter.com/cambrianentropy
  email:             cambrianentropy@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-167458623-1

